# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.9.1
group=com.theendercore.visible_toggle_sprint
java_version=21

# Dependencies
fzzy_config=0.6.9+1.21.3

# Common
minecraft_version=1.21.4
mod_name=VisibleToggleSprint
mod_author=TheEnderCore
mod_id=visible_toggle_sprint
license=MIT
credits=Ender The Core
description=A simple mod to make toggle sprint & sneak better!
minecraft_version_range=[1.21.4,)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Fabric
fabric_version=0.119.2+1.21.4
fabric_loader_version=0.16.14

# NeoForge
neoforge_version=21.4.135
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
